antminermonitor/blueprints/asicminer/models/__init__.py
from .miner import Miner
from .miner_model import MinerModel
from .settings import Settings

antminermonitor/blueprints/asicminer/models/miner.py
from antminermonitor.extensions import db


class Miner(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    ip = db.Column(db.String(15), unique=True, nullable=False)
    model_id = db.Column(db.Integer, db.ForeignKey('miner_model.id'),
                         nullable=False)
    model = db.relationship("MinerModel", backref="miners")
    remarks = db.Column(db.String(255), nullable=True)

    def __repr__(self):
        return "Miner(ip='{}', model='{}', remarks='{}')" \
            .format(self.ip, self.model, self.remarks)

antminermonitor/blueprints/asicminer/models/miner_model.py
from antminermonitor.extensions import db


class MinerModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    model = db.Column(db.String(15), unique=True, nullable=False)
    chips = db.Column(db.String(24), nullable=False)
    temp_keys = db.Column(db.String(5), nullable=False)
    description = db.Column(db.String(255), nullable=True)

    def __repr__(self):
        return "MinerModel(model='{}', chips={}, description='{}')" \
            .format(self.model, self.chips, self.description)

antminermonitor/blueprints/asicminer/models/settings.py
from antminermonitor.extensions import db


class Settings(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)
    value = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(255))

    def __repr__(self):
        return "Settings(name='{}', value={}, description='{}')" \
            .format(self.name, self.value, self.description)

antminermonitor/blueprints/asicminer/__init__.py
from antminermonitor.blueprints.asicminer.views.antminer import antminer
from antminermonitor.blueprints.asicminer.views.antminer_json import antminer_json

antminermonitor/blueprints/asicminer/views/antminer.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    current_app,
)
from lib.pycgminer import (
    get_pools,
    get_stats,
)
from lib.util_hashrate import update_unit_and_value
from sqlalchemy.exc import IntegrityError
from antminermonitor.extensions import db
from antminermonitor.blueprints.asicminer.models import (
    Miner,
    MinerModel,
)
import re
from datetime import timedelta
import time

antminer = Blueprint('antminer', __name__, template_folder='../templates')


@antminer.route('/')
def miners():
    # Init variables
    start = time.clock()
    miners = Miner.query.all()
    models = MinerModel.query.all()
    active_miners = []
    inactive_miners = []
    workers = {}
    miner_chips = {}
    temperatures = {}
    fans = {}
    hash_rates = {}
    hw_error_rates = {}
    uptimes = {}
    total_hash_rate_per_model = {"L3+": {"value": 0, "unit": "MH/s"},
                                 "S7":  {"value": 0, "unit": "GH/s"},
                                 "S9":  {"value": 0, "unit": "GH/s"},
                                 "D3":  {"value": 0, "unit": "MH/s"},
                                 "T9":  {"value": 0, "unit": "GH/s"},
                                 "T9+": {"value": 0, "unit": "GH/s"},
                                 "A3":  {"value": 0, "unit": "GH/s"},
                                 "L3":  {"value": 0, "unit": "MH/s"},
                                 "R4":  {"value": 0, "unit": "TH/s"},
                                 "V9":  {"value": 0, "unit": "GH/s"},
                                 "X3":  {"value": 0, "unit": "KH/s"}, }

    errors = False
    miner_errors = {}

    for miner in miners:
        miner_stats = get_stats(miner.ip)
        # if miner not accessible
        if miner_stats['STATUS'][0]['STATUS'] == 'error':
            errors = True
            inactive_miners.append(miner)
        else:
            # Get worker name
            miner_pools = get_pools(miner.ip)
            worker = miner_pools['POOLS'][0]['User']
            # Get miner's ASIC chips
            asic_chains = [
                miner_stats['STATS'][1][chain]
                for chain in miner_stats['STATS'][1].keys()
                if "chain_acs" in chain
            ]
            # count number of working chips
            O = [str(o).count('o') for o in asic_chains]
            Os = sum(O)
            # count number of defective chips
            X = [str(x).count('x') for x in asic_chains]
            Xs = sum(X)
            # get number of in-active chips
            _dash_chips = [str(x).count('-') for x in asic_chains]
            _dash_chips = sum(_dash_chips)
            # Get total number of chips according to miner's model
            # convert miner.model.chips to int list and sum
            chips_list = [int(y) for y in str(miner.model.chips).split(',')]
            total_chips = sum(chips_list)
            # Get the temperatures of the miner according to miner's model
            temps = [
                int(miner_stats['STATS'][1][temp]) for temp in sorted(
                    miner_stats['STATS'][1].keys(), key=lambda x: str(x))
                if re.search(miner.model.temp_keys + '[0-9]', temp)
                if miner_stats['STATS'][1][temp] != 0
            ]
            # Get fan speeds
            fan_speeds = [
                miner_stats['STATS'][1][fan] for fan in sorted(
                    miner_stats['STATS'][1].keys(), key=lambda x: str(x))
                if re.search("fan" + '[0-9]', fan)
                if miner_stats['STATS'][1][fan] != 0
            ]
            # Get GH/S 5s
            ghs5s = float(str(miner_stats['STATS'][1]['GHS 5s']))
            # Get HW Errors
            hw_error_rate = miner_stats['STATS'][1]['Device Hardware%']
            # Get uptime
            uptime = timedelta(seconds=miner_stats['STATS'][1]['Elapsed'])
            #
            workers.update({miner.ip: worker})
            miner_chips.update({
                miner.ip: {
                    'status': {
                        'Os': Os,
                        'Xs': Xs,
                        '-': _dash_chips
                    },
                    'total': total_chips,
                }
            })
            temperatures.update({miner.ip: temps})
            fans.update({miner.ip: {"speeds": fan_speeds}})
            value, unit = update_unit_and_value(
                ghs5s, total_hash_rate_per_model[miner.model.model]['unit'])
            hash_rates.update({miner.ip: "{:3.2f} {}".format(value, unit)})
            hw_error_rates.update({miner.ip: hw_error_rate})
            uptimes.update({miner.ip: uptime})
            total_hash_rate_per_model[miner.model.model]["value"] += ghs5s
            active_miners.append(miner)

            # Flash error messages
            if Xs > 0:
                error_message = ("[WARNING] '{}' chips are defective on "
                                 "miner '{}'.").format(Xs, miner.ip)
                current_app.logger.warning(error_message)
                flash(error_message, "warning")
                errors = True
                miner_errors.update({miner.ip: error_message})
            if Os + Xs < total_chips:
                error_message = (
                    "[ERROR] ASIC chips are missing from miner "
                    "'{}'. Your Antminer '{}' has '{}/{} chips'.").format(
                        miner.ip, miner.model.model, Os + Xs, total_chips)
                current_app.logger.error(error_message)
                flash(error_message, "error")
                errors = True
                miner_errors.update({miner.ip: error_message})
            if temps:
                if max(temps) >= 80:
                    error_message = ("[WARNING] High temperatures on "
                                     "miner '{}'.").format(miner.ip)
                    current_app.logger.warning(error_message)
                    flash(error_message, "warning")
            if not temps:
                temperatures.update({miner.ip: 0})
                error_message = ("[ERROR] Could not retrieve temperatures "
                                 "from miner '{}'.").format(miner.ip)
                current_app.logger.warning(error_message)
                flash(error_message, "error")

    # Flash success/info message
    if not miners:
        error_message = ("[INFO] No miners added yet. "
                         "Please add miners using the above form.")
        current_app.logger.info(error_message)
        flash(error_message, "info")
    elif not errors:
        error_message = ("[INFO] All miners are operating normal. "
                         "No errors found.")
        current_app.logger.info(error_message)
        flash(error_message, "info")

    # flash("[INFO] Check chips on your miner", "info")
    # flash("[SUCCESS] Miner added successfully", "success")
    # flash("[WARNING] Check temperatures on your miner", "warning")
    # flash("[ERROR] Check board(s) on your miner", "error")

    # Convert the total_hash_rate_per_model into a data structure that the
    # template can consume.
    total_hash_rate_per_model_temp = {}
    for key in total_hash_rate_per_model:
        value, unit = update_unit_and_value(
            total_hash_rate_per_model[key]["value"],
            total_hash_rate_per_model[key]["unit"])
        if value > 0:
            total_hash_rate_per_model_temp[key] = "{:3.2f} {}".format(
                value, unit)

    end = time.clock()
    loading_time = end - start
    return render_template(
        'asicminer/home.html',
        version=current_app.config['__VERSION__'],
        models=models,
        active_miners=active_miners,
        inactive_miners=inactive_miners,
        workers=workers,
        miner_chips=miner_chips,
        temperatures=temperatures,
        fans=fans,
        hash_rates=hash_rates,
        hw_error_rates=hw_error_rates,
        uptimes=uptimes,
        total_hash_rate_per_model=total_hash_rate_per_model_temp,
        loading_time=loading_time,
        miner_errors=miner_errors,
    )


@antminer.route('/add', methods=['POST'])
def add_miner():
    miner_ip = request.form['ip']
    miner_model_id = request.form.get('model_id')
    miner_remarks = request.form['remarks']

    # exists = Miner.query.filter_by(ip="").first()
    # if exists:
    #    return "IP Address already added"

    try:
        miner = Miner(
            ip=miner_ip, model_id=miner_model_id, remarks=miner_remarks)
        db.session.add(miner)
        db.session.commit()
        flash("Miner with IP Address {} added successfully".format(miner.ip),
              "success")
    except IntegrityError:
        db.session.rollback()
        flash("IP Address {} already added".format(miner_ip), "error")

    return redirect(url_for('antminer.miners'))


@antminer.route('/delete/<id>')
def delete_miner(id):
    miner = Miner.query.filter_by(id=int(id)).first()
    db.session.delete(miner)
    db.session.commit()
    return redirect(url_for('antminer.miners'))

antminermonitor/blueprints/asicminer/views/antminer_json.py
from flask import Blueprint, jsonify
from lib.pycgminer import (get_summary,
                           get_pools,
                           get_stats,
                           )

antminer_json = Blueprint('antminer_json',
                          __name__,
                          template_folder='../templates',
                          )


@antminer_json.route('/<ip>/summary')
def summary(ip):
    output = get_summary(ip)
    return jsonify(output)


@antminer_json.route('/<ip>/pools')
def pools(ip):
    output = get_pools(ip)
    return jsonify(output)


@antminer_json.route('/<ip>/stats')
def stats(ip):
    output = get_stats(ip)
    return jsonify(output)

antminermonitor/blueprints/asicminer/templates/asicminer/home.1.html
{% extends 'layouts/base.html' %}

{% block meta_description %}
Antminer Monitor, antminer, monitor, antmon, bitmain, bitcoin, litecoin, dash, 
cryptocurrency, crypto, miner, mine, mining
{% endblock %}
{% block title %}Ubimin Monitor 0.1 <!--{{ version }}-->{% endblock %}

{% block body %}
<h2>Ubimin Monitor 0.1 <!--{{ version }}--></h2>
<fieldset>
<legend>Reloj proxima actualizacion</legend>
<b id="countdown"></b>
</fieldset>
<div class="row">
    <div class="col-md-6">
      <fieldset name="add">
          <legend>Añadir Minero</legend>
          <form action="{{ url_for('antminer.add_miner') }}" method="POST">
              <div class="addminer_container">
                  <div>
                      <label for="ip">IP Address: </label>
                  </div>
                  <div>
                      <input class="form-control" required type="text" name="ip">
                  </div>
                  <div>
                      <label for="model_id">Modelo: </label>
                  </div>
                  <div>
                      <select required name="model_id" class="form-control">
                          <option disabled selected value> -- select an option --</option>
                          {%- for model in models|sort(attribute="model") %}
                              <option value="{{ model.id }}">{{ model.model }} - {{ model.description }}</option>
                          {%- endfor %}
                      </select>
                  </div>
                  <div>
                      <label for="remarks">Remarks: </label>
                  </div>
                  <div>
                      <input class="form-control" type="text" name="remarks">
                  </div>
                  <p><input class="btn btn-default" type="submit" value="Añadir modelo"></p>
              </div>
          </form>
      </fieldset>
    </div>
    <div></div>
    <div class="col-md-6">
        <fieldset name="total_hashrate" style="height:130px">
            <legend>Total hashrate por model (5s)</legend>
            <ul class="list-group">
                {%- for model in total_hash_rate_per_model|sort %}
                    <li class="list-group-item"><u>{{ model }}:</u> <strong>{{ total_hash_rate_per_model[model] }}</strong>
                    </li>
                {%- endfor %}
            </ul>
        </fieldset>
    </div>
</div>
<br>

{%- with messages = get_flashed_messages(with_categories=true) %}
    {%- if messages %}
        {%- for category, message in messages %}
            <div class="alert {{ category }}">
                <strong>{{ message }}</strong>
            </div>
        {%- endfor %}
    {%- endif %}
{%- endwith %}

{%- if inactive_miners %}
    <fieldset name="inactive_miner_list">
        <legend>In-active Miners ({{ inactive_miners|length }})</legend>
        <table style="width:100%">
            <tr>
                <th>IP Address</th>
                <th>Model</th>
                <th>Remarks</th>
                <th>Status</th>
                <th>Remove</th>
            </tr>
            {%- for inactive_miner in inactive_miners|sort(attribute='ip') %}
                <tr>
                    <td><a target="_blank" href="http://{{ inactive_miner.ip }}">{{ inactive_miner.ip }}</a></td>
                    <td>{{ inactive_miner.model.model }}</td>
                    <td>{{ inactive_miner.remarks }}</td>
                    <td>Error: Check connection or IP Address</td>
                    <td><a href={{ url_for('antminer.delete_miner', id=inactive_miner.id) }}><img src="/static/images/assets/remove.png"></img></a></td>
                </tr>
            {%- endfor %}
        </table>
    </fieldset>
{%- endif %}
<br>

<fieldset name="active_miner_list">
    <legend>Mineros activos ({{ active_miners|length }})</legend>
    <table class="table table-hover" style="width:100%">
        <tr>
            <th>IP Address</th>
            <th>Worker</th>
            <th>Model</th>
            <th>Remarks</th>
            <th title="'O' means OK">Chips (Os)</th>
            <th title="'X' means defective">Chips (Xs)</th>
            <th title="'-' means instability of the power supply voltage or the defective hash board">Chips (-)</th>
            <th>Chip Temp(C)</th>
            <th>Fan speeds (rpm)</th>
            <th>Hashrate (5s)</th>
            <th>HW Error Rate %</th>
            <th>Uptime</th>
            <th>Status</th>
            <!--<th>JSON Info</th>-->
            <th>Remove</th>
        </tr>
        {%- for active_miner in active_miners|sort(attribute='ip') %}
            <tr{%- if active_miner.ip in miner_errors %} class="danger"{%- endif %}>
                <td><a target="_blank" href="http://{{ active_miner.ip }}">{{ active_miner.ip }}</a></td>
                <td>{{ workers[active_miner.ip] }}</td>
                <td title="{{ active_miner.model.description }}">{{ active_miner.model.model }}</td>
                <td>{{ active_miner.remarks }}</td>
                <td>{{ miner_chips[active_miner.ip]['status']['Os'] }}</td>
                <td>{{ miner_chips[active_miner.ip]['status']['Xs'] }}</td>
                <td>{{ miner_chips[active_miner.ip]['status']['-'] }}</td>
                <td>{{ temperatures[active_miner.ip] }}</td>
                <td>{{ fans[active_miner.ip].speeds }}</td>
                <td>{{ hash_rates[active_miner.ip] }}</td>
                <td>{{ hw_error_rates[active_miner.ip] }}</td>
                <td>{{ uptimes[active_miner.ip] }}</td>
                <td title="{%- if active_miner.ip in miner_errors %}{{ miner_errors[active_miner.ip] }}{%- endif %}">
                    {%- if active_miner.ip in miner_errors %}Check your miner{%- else %}OK{%- endif %}</td>
                <!--<td><a target="_blank" href="/{{ active_miner.ip }}/summary">Summary</a> |
                    <a target="_blank" href="/{{ active_miner.ip }}/pools">Pools</a> |
                    <a target="_blank" href="/{{ active_miner.ip }}/stats">Stats</a></td>-->
                <td><a href={{ url_for('antminer.delete_miner', id=active_miner.id) }}><img src="/static/images/assets/remove.png"></img></a></td>
            </tr>
        {%- endfor %}
    </table>
</fieldset>
{% endblock %}

antminermonitor/blueprints/asicminer/templates/asicminer/home.html
{% extends 'layouts/base.html' %}

{% block meta_description %}
Antminer Monitor, antminer, monitor, antmon, bitmain, bitcoin, litecoin, dash, 
cryptocurrency, crypto, miner, mine, mining
{% endblock %}
{% block title %}Ubimin Monitor 0.1 <!--{{ version }}-->{% endblock %}

{% block body %}

<link rel="stylesheet" href="{{ url_for('static', filename='styles/css/style.css') }}" /><!--Menu-->
<link rel="stylesheet" href="{{ url_for('static', filename='styles/css/bootstrap.css') }}" /> <!--Botones-->
<link rel='stylesheet' href="{{ url_for('static', filename='styles/css/bootstrap.min.css') }}"/> <!--Notificaciiones-->
<link rel="stylesheet" href="{{ url_for('static', filename='styles/css/noty.css') }}"/> <!--Notificaciiones-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
     <!--Menu-->
     <style type="text/css">
         a, a:visited, a:active, a:link {
          text-decoration:none;
          color:#0071BC;
          display: none;
         }
        nav ul li:hover > a{
          text-decoration:none;
          color:#0071BC;
          display: block;
        }
        .activeMO{
            background-color: #0071BC !important;
        }
        .activeA{
            color: white !important;
        }

          
      </style>


<script>

    jQuery(document).ready(function(){ 
        $(".oculto").hide();         
        $(".oculto")[2].style = "display:block";           
        $(".MO").click(function(){
            var nodo = $(this).attr("href");  
            if ($(nodo).is(":visible")){
                //$(nodo).hide();
                return false;
            }else{
                $(".oculto").hide();                             
                $(nodo).fadeToggle( "slow" );
                return false;
            }
        });
        
    }); 
    function changeColor1(i){
        console.log("entro.--",i);
        $("[id*=menuFloat]").removeClass("activeMO");
        $("[id*=menuFloat] a").removeClass("activeA");
        $("[id*=menuFloat] span").removeClass("activeA");
        $('#menuFloat'+i).addClass("activeMO");
        $('#menuFloat'+i +" a").addClass("activeA");
        $('#menuFloat'+i +" span").addClass("activeA");
    }
</script>

<br/><br/><h2>Ubimin Monitor 0.1 <!--{{ version }}--></h2>  

<div class="circulo" style="position:absolute;right:150px; top:15px;z-index:3;">
    <h1 style="color:white;margin-bottom: 0;" > <b id="countdown"></b> </h1><br>
    <h5 style="color:white; margin-top:0;"> Seg</h5> 
</div>

<div style="position:absolute;right:150px; top:130px;z-index:3;">
    <h4>Actualizaci&oacute;n</h4>
</div>

<div id="div1" class="oculto">
    <br/><br/>
    <br/><br/>
    {% set variable = [] %}
    {%- with messages = get_flashed_messages(with_categories=true) %}
    {%- if messages %}
    {%- for category, message in messages %}
    <div class="alert {{ category }}">
    <strong>{{ message }}</strong>
        {%- if category=="danger" %}
            {% if variable.append(1) %} {%- endif %}                                                       
        {%- else %}
            {% if variable.append(0) %} {%- endif %}            
        {%- endif %}
    </div>
    {%- endfor %}
    {%- endif %}
    {%- endwith %}
        
    {%- if inactive_miners %}
        <fieldset name="inactive_miner_list">
            <legend>In-active Miners ({{ inactive_miners|length }})</legend>
            <table style="width:100%">
                <tr>
                    <th>IP Address</th>
                    <th>Model</th>
                    <th>Remarks</th>
                    <th>Status</th>
                    <th>Remove</th>
                </tr>
                {%- for inactive_miner in inactive_miners|sort(attribute='ip') %}
                    <tr>
                        <td><a target="_blank" href="http://{{ inactive_miner.ip }}">{{ inactive_miner.ip }}</a></td>
                        <td>{{ inactive_miner.model.model }}</td>
                        <td>{{ inactive_miner.remarks }}</td>
                        <td>Error: Check connection or IP Address</td>
                        <td><a href={{ url_for('antminer.delete_miner', id=inactive_miner.id) }}><img src="/static/images/assets/remove.png"></img></a></td>
                    </tr>
                {%- endfor %}
            </table>
        </fieldset>
    {%- endif %}
    <br>
</div>

<br/><br/>
<div id="div2" class="oculto">
    <fieldset name="add">
        <legend>Añadir Minero</legend>
        <form action="{{ url_for('antminer.add_miner') }}" method="POST">
            <div style="align-items: center;justify-content: center;" class="addminer_container">
                <div>
                    <label for="ip">IP Address: </label>
                </div>

                <div>
                    <input class="form-control" required type="text" name="ip">
                </div>

                <div>
                    <label for="model_id">Modelo: </label>
                </div>

                <div>
                    <select required name="model_id" class="form-control">
                        <option disabled selected value> -- select an option --</option>
                        {%- for model in models|sort(attribute="model") %}
                            <option value="{{ model.id }}">{{ model.model }} - {{ model.description }}</option>
                        {%- endfor %}
                    </select>
                </div>

                <div>
                    <label for="remarks">Remarks: </label>
                </div>
            
                <div>
                    <input class="form-control" type="text" name="remarks">
                </div>
                
                <p><input class="btn btn-default" type="submit" value="Añadir modelo"></p>
            </div>
        </form>
    </fieldset>
</div>

<div id="div3" class="oculto">
    <fieldset name="total_hashrate" style="height:130px">
        <legend>Total hashrate por model (5s)</legend>
            <ul class="flex-container">
                {%- for model in total_hash_rate_per_model|sort %}
                    <li class="flex-item">
                        <strong><h1></br></br>{{ total_hash_rate_per_model[model] }} </br>
                                        __________</br>
                                    </br>{{ model }}
                            </h1></strong>                       
                    </li>
                {% endfor %}
            </ul>
    </fieldset>
</div>
<br>

<section>
    <div id="tabla">
    <fieldset name="active_miner_list">
        <legend>Mineros activos ({{ active_miners|length }})</legend>
        <table class="table table-hover" style="width:100%">
            <tr>
                <th>IP Address</th>
                <th>Worker</th>
                <th>Model</th>
                <th>Remarks</th>
                <th title="'O' means OK">Chips (Os)</th>
                <th title="'X' means defective">Chips (Xs)</th>
                <th title="'-' means instability of the power supply voltage or the defective hash board">Chips (-)</th>
                <th>Chip Temp(C)</th>
                <th>Fan speeds (rpm)</th>
                <th>Hashrate (5s)</th>
                <th>HW Error Rate %</th>
                <th>Uptime</th>
                <th>Status</th>
                <th>Remove</th>
                <th>Conf</th>
            </tr>
            {%- for active_miner in active_miners|sort(attribute='ip') %}
                <tr{%- if active_miner.ip in miner_errors %} class="danger"{%- endif %}>
                    <td><a target="_blank" href="http://{{ active_miner.ip }}">{{ active_miner.ip }}</a></td>
                    <td>{{ workers[active_miner.ip] }}</td>
                    <td title="{{ active_miner.model.description }}">{{ active_miner.model.model }}</td>
                    <td>{{ active_miner.remarks }}</td>
                    <td>{{ miner_chips[active_miner.ip]['status']['Os'] }}</td>
                    <td>{{ miner_chips[active_miner.ip]['status']['Xs'] }}</td>
                    <td>{{ miner_chips[active_miner.ip]['status']['-'] }}</td>
                    <td>{{ temperatures[active_miner.ip] }}</td>
                    <td>{{ fans[active_miner.ip].speeds }}</td>
                    <td>{{ hash_rates[active_miner.ip] }}</td>
                    <td>{{ hw_error_rates[active_miner.ip] }}</td>
                    <td>{{ uptimes[active_miner.ip] }}</td>

                    <td title="{%- if active_miner.ip in miner_errors %}{{ miner_errors[active_miner.ip] }}{%- endif %}">
                        {%- if active_miner.ip in miner_errors %}Check your miner{%- else %}OK{%- endif %}</td>
                    <td><a href={{ url_for('antminer.delete_miner', id=active_miner.id) }}>
                        <button type="button"> <i class="glyphicon glyphicon-remove"></i> </button> </a>
                    </td>

                    <td><p><a href="#ex1" rel="modal:open">
                        <button type="button"> <i class="glyphicon glyphicon-wrench"></i></button></a></p>
                    </td>
                </tr>
            {%- endfor %}

        </table>
    </fieldset>
    </div>
</section>

<!--MENU-->
<div class="menubar" >
    <nav>
        <ul>
            <li id="menuFloat1" onclick="changeColor1(1)" style="margin-bottom:10px;"><a onclick="changeColor1(1)" href="#div1" class='MO'>Notificaciones
                </a><span><i class="glyphicon glyphicon-bell"></i></span> 
                {%- if variable == [1] %} 
                    <span style="float:right; left:9px; top:0px;position:relative;" class="badge">1 </span>
                {% else %} 
                {%- endif %} </li>
            <li id="menuFloat2" onclick="changeColor1(2)" style="margin-bottom:10px;"><a onclick="changeColor1(2)" href="#div2" class='MO'>Añadir Minero</a><span><i class="glyphicon glyphicon-plus"></i></span></li>
            <li id="menuFloat3" class="activeMO" onclick="changeColor1(3)" style="margin-bottom:10px;"><a href="#div3" onclick="changeColor1(3)" class='MO activeA'>Total hashrate</a><span class="activeA"><i class="glyphicon glyphicon-time"></i></span></li>
        </ul>
    </nav>
</div>

<footer>
    <div>
        </br>
        <center>
        &copy; Copyright 2017-2018 by <a href="https://www.ubitica.com">Ubitica</a>.
        </br></br>
        </center>
    </div>
</footer>

<!-- jQuery Para Modal :) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />

<div id="ex1" class="modal">
        <h3>Apagar Si</h3>
        <input type="checkbox" name="checkbox" value="">
        <label>Hash </label>
        <input type="text" id="hash" name="hash" size="10" />
        <br />
        <br />
        <h3>Reiniciar Si</h3>
        <input type="checkbox" name="checkbox" value="">
        <label>Temp > </label>
        <input type="text" id="temp" name="temp" size="10" />
        <br />
        <input type="checkbox" name="checkbox" value="">
        <label>RPM < </label>
        <input type="text" id="rpm" name="rpm" size="10" />
        <br />
        <p></p>
         <a href="#" rel="modal:close">

            <button>Cancelar</button>
         </a>
            <button>Aceptar</button>
</div>

{% endblock %}